inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'scratch.rb'
    - 'spec/internal/**/*'
    - 'lib/curator/archivable.rb'
    - 'lib/curator/services/remote_service.rb'
    - 'db/**/*'
    - 'app/services/curator/filestreams/file_set_factory_service.rb'
  DisplayCopNames: true
  DisabledByDefault: true
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  Enabled: true

Gemspec/OrderedDependencies:
  Enabled: true

####################### LAYOUT ###############################
Layout/AlignArray:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/AlignArguments:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/EmptyComment:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/IndentFirstHashElement:
  Enabled: true
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/LeadingBlankLines:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

####################### LINTING ###############################

Lint/AmbiguousOperator:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/StringConversionInInterpolation:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true
  Exclude:
    - 'spec/**/*'

####################### NAMING ###############################

Naming/AccessorMethodName:
  Enabled: true

####################### STYLE ###############################

Style/AccessModifierDeclarations:
  Enabled: true

Style/BlockComments:
  Enabled: true
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/DefWithParentheses:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EvalWithLocation:
  Enabled: true

Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  Exclude:
    - 'spec/**/*'

Style/IfUnlessModifier:
  Enabled: true

Style/Lambda:
  Enabled: true

Style/MixinUsage:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/Next:
  Enabled: true

Style/NumericLiterals:
  Enabled: true

Style/Proc:
  Enabled: true
