---
require: rubocop-rspec

AllCops:
  RSpec:
    Patterns:
    - _spec.rb
    - "(?:^|/)spec/"

RSpec/AnyInstance:
  Enabled: true

RSpec/BeEql:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true

RSpec/DescribedClass:
  SkipBlocks: false
  Enabled: true

RSpec/DescribeMethod:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true
  CustomIncludeMethods: []

RSpec/ExampleLength:
  Enabled: true
  Max: 5

RSpec/ExampleWording:
  Enabled: true
  CustomTransform:
    be: is
    have: has
    not: does not
  IgnoredWords: []

RSpec/ExpectActual:
  Enabled: true

RSpec/ExpectOutput:
  Enabled: true

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: true
  EnforcedStyle: implicit
  SupportedStyles:
  - implicit
  - each
  - example

RSpec/ImplicitExpect:
  Enabled: true
  EnforcedStyle: is_expected
  SupportedStyles:
  - is_expected
  - should

RSpec/InstanceVariable:
  AssignmentOnly: false
  Enabled: true

RSpec/LeadingSubject:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/MessageChain:
  Enabled: true

RSpec/MessageExpectation:
  Enabled: false
  EnforcedStyle: allow
  SupportedStyles:
  - allow
  - expect

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: have_received
  SupportedStyles:
  - have_received
  - receive

RSpec/MultipleDescribes:
  Enabled: true

RSpec/NamedSubject:
  Enabled: true

RSpec/NestedGroups:
  Enabled: true
  Max: 5

RSpec/NotToNot:
  EnforcedStyle: not_to
  SupportedStyles:
  - not_to
  - to_not
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: true

RSpec/RepeatedExample:
  Enabled: true

RSpec/SingleArgumentMessageChain:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true

RSpec/SubjectStub:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true
  IgnoreSymbolicNames: false
