# Place any default configuration for solr_wrapper here
port: 8984
version: 8.9.0
instance_dir: ./spec/internal/tmp/solr-test
collection:
  persist: false
  dir: ./spec/internal/solr/conf/
  name: curator_test
