minio: &minio
  service: S3
  access_key_id: <%= ENV['MINIO_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['MINIO_SECRET_KEY'] %>
  region: <%= ENV['MINIO_REGION_NAME'] %>
  endpoint: <%= ENV['MINIO_URL'] %>
  force_path_style: true

primary:
  <<: *minio
  bucket: sourceimages

derivatives:
  <<: *minio
  bucket: derivatives
  public: true
